# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "https://mfkslndpuadwxlmhhclb.supabase.co"
SUPABASE_KEY = "sb_publishable_F-I45NhmkeDBInhRf0ixZA_OuPFKFLt"
STRAVA_CLIENT_ID= "196554"
STRAVA_CLIENT_SECRET= "2282e5bdfbfbe6bec2af2b76567d3cab5a85fc50"
STRAVA_REFRESH_TOKEN= "ef0876e17766f7f21f2f1fe1c50890c0962f6afd"
